### ISSUE TITLE
Error message using Kobold

### ISSUE THREAD

**Issue by TehNomad** [anon998/simple-proxy-for-tavern#14]
I'm using [KoboldAI 4-bit branch](https://github.com/0cc4m/KoboldAI/tree/4bit-plugin) as my backend and I'm getting the following error message when I submit a prompt in SillyTavern to the proxy:

TypeError: Cannot set properties of undefined (setting 'abortPreviousRequest')
    at koboldGenerateStreamUI2 (file://***/simple-proxy-for-tavern/src/kobold-stream.mjs:246:30)
    at koboldGenerate (file://***/simple-proxy-for-tavern/src/backends.mjs:87:11)
    at getChatCompletions (file://***/simple-proxy-for-tavern/src/index.mjs:490:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server.<anonymous> (file://***/simple-proxy-for-tavern/src/index.mjs:561:9)

**Comment by TehNomad** [comment]
Yes, that fixed that error. Now it seems like it's getting stuck on "loading options." I'll investigate a bit on my own, but do you have any suggestions on how to debug this?

**Comment by TehNomad** [comment]
Yep, keeping the window open also works for me. Thanks for looking into both of those issues.
