### ISSUE TITLE
Invalid csrf token for SillyTavern 1.92 Release

### ISSUE THREAD

**Issue by GF-110** [anon998/simple-proxy-for-tavern#23]
SillyTavern is retiring the Main branch.

When the proxy is used with the Release branch, it gives the following error:

ForbiddenError: invalid csrf token
    at doubleCsrf (C:\text-gen\SillyTavern\node_modules\csrf-csrf\lib\cjs\index.cjs:18:61)
    at Object.<anonymous> (C:\text-gen\SillyTavern\server.js:301:49)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

**Comment by GF-110** [comment]
Unable to replicate.
